/**
 * This file was generated by the Jeddict
 */
package com.udea.mascotas;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author Daniel
 */
@Entity
public class Mascota {

    @Column(name = "id")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "nombreMascota", nullable = false)
    @Basic
    @NotNull(message = "No puede ser vacÃ­o")
    private String nombreMascota;

    @Column(name = "raza", nullable = false)
    @Basic
    @NotNull(message = "No puede ser vacÃ­o")
    private String raza;

    @Column(name = "cantidad", nullable = false)
    @Basic
    @NotNull(message = "No puede ser vacÃ­o")
    @Min(value = 0, message = "MÃ­nimo 0")
    private int cantidad;

    @Column(name = "precio", nullable = false)
    @Basic
    @NotNull(message = "No puede ser vacÃ­o")
    private Double precio;

    @Column(name = "edad", nullable = false)
    @Basic
    @NotNull(message = "No puede ser vacÃ­o")
    @Min(value = 0, message = "MÃ­nimo 0")
    private int edad;

    @Column(name = "imagen")
    @Basic
    private String imagen;

    @ManyToOne(targetEntity = TipoMascota.class)
    private TipoMascota tipoMascota;

    public Mascota(Long id, String nombreMascota, String raza, int cantidad, Double precio, int edad, String imagen, TipoMascota tipoMascota) {
        this.id = id;
        this.nombreMascota = nombreMascota;
        this.raza = raza;
        this.cantidad = cantidad;
        this.precio = precio;
        this.edad = edad;
        this.imagen = imagen;
        this.tipoMascota = tipoMascota;
    }

    public Mascota() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombreMascota() {
        return this.nombreMascota;
    }

    public void setNombreMascota(String nombreMascota) {
        this.nombreMascota = nombreMascota;
    }

    public String getRaza() {
        return this.raza;
    }

    public void setRaza(String raza) {
        this.raza = raza;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public Double getPrecio() {
        return this.precio;
    }

    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public int getEdad() {
        return this.edad;
    }

    public void setEdad(int edad) {
        this.edad = edad;
    }

    public String getImagen() {
        return this.imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public TipoMascota getTipoMascota() {
        return this.tipoMascota;
    }

    public void setTipoMascota(TipoMascota tipoMascota) {
        this.tipoMascota = tipoMascota;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Mascota other = (Mascota) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "Mascota{" + " id=" + id + '}';
    }

}